// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: svc/base.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseRequest_Status int32

const (
	LeaseRequest_unused     LeaseRequest_Status = 0
	LeaseRequest_Pending    LeaseRequest_Status = 1
	LeaseRequest_Fulfulling LeaseRequest_Status = 2
	LeaseRequest_Fulfilled  LeaseRequest_Status = 3
)

// Enum value maps for LeaseRequest_Status.
var (
	LeaseRequest_Status_name = map[int32]string{
		0: "unused",
		1: "Pending",
		2: "Fulfulling",
		3: "Fulfilled",
	}
	LeaseRequest_Status_value = map[string]int32{
		"unused":     0,
		"Pending":    1,
		"Fulfulling": 2,
		"Fulfilled":  3,
	}
)

func (x LeaseRequest_Status) Enum() *LeaseRequest_Status {
	p := new(LeaseRequest_Status)
	*p = x
	return p
}

func (x LeaseRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_svc_base_proto_enumTypes[0].Descriptor()
}

func (LeaseRequest_Status) Type() protoreflect.EnumType {
	return &file_svc_base_proto_enumTypes[0]
}

func (x LeaseRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseRequest_Status.Descriptor instead.
func (LeaseRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_svc_base_proto_rawDescGZIP(), []int{0, 0}
}

type LeaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaseRequestId string              `protobuf:"bytes,1,opt,name=lease_request_id,json=leaseRequestId,proto3" json:"lease_request_id,omitempty"`
	ClientId       string              `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Region         string              `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Tag            string              `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Status         LeaseRequest_Status `protobuf:"varint,5,opt,name=status,proto3,enum=volchestrator.LeaseRequest_Status" json:"status,omitempty"`
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_svc_base_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseRequest) GetLeaseRequestId() string {
	if x != nil {
		return x.LeaseRequestId
	}
	return ""
}

func (x *LeaseRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaseRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LeaseRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *LeaseRequest) GetStatus() LeaseRequest_Status {
	if x != nil {
		return x.Status
	}
	return LeaseRequest_unused
}

var File_svc_base_proto protoreflect.FileDescriptor

var file_svc_base_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x76, 0x63, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x76, 0x6f, 0x6c, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0xfd, 0x01, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x10, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x22, 0x2e, 0x76, 0x6f, 0x6c, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x40, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x6e, 0x75, 0x73, 0x65,
	0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x75, 0x6c, 0x66, 0x75, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x10, 0x02,
	0x12, 0x0d, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x42,
	0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x30,
	0x70, 0x72, 0x30, 0x63, 0x6b, 0x35, 0x2f, 0x76, 0x6f, 0x6c, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_base_proto_rawDescOnce sync.Once
	file_svc_base_proto_rawDescData = file_svc_base_proto_rawDesc
)

func file_svc_base_proto_rawDescGZIP() []byte {
	file_svc_base_proto_rawDescOnce.Do(func() {
		file_svc_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_base_proto_rawDescData)
	})
	return file_svc_base_proto_rawDescData
}

var file_svc_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svc_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_svc_base_proto_goTypes = []interface{}{
	(LeaseRequest_Status)(0), // 0: volchestrator.LeaseRequest.Status
	(*LeaseRequest)(nil),     // 1: volchestrator.LeaseRequest
}
var file_svc_base_proto_depIdxs = []int32{
	0, // 0: volchestrator.LeaseRequest.status:type_name -> volchestrator.LeaseRequest.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_svc_base_proto_init() }
func file_svc_base_proto_init() {
	if File_svc_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_base_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_base_proto_goTypes,
		DependencyIndexes: file_svc_base_proto_depIdxs,
		EnumInfos:         file_svc_base_proto_enumTypes,
		MessageInfos:      file_svc_base_proto_msgTypes,
	}.Build()
	File_svc_base_proto = out.File
	file_svc_base_proto_rawDesc = nil
	file_svc_base_proto_goTypes = nil
	file_svc_base_proto_depIdxs = nil
}
